import { SessionRequest } from "@/contexts/AppContext";

export const mockSessions: SessionRequest[] = [
  {
    id: "1",
    patientId: "p1",
    patientName: "Kwame Mensah",
    patientGender: "Male",
    patientAgeRange: "45-55",
    specialService: "Cardiology",
    hospitalId: "h1",
    hospitalName: "Korle Bu Teaching Hospital",
    status: "pending",
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    requesterName: "Kwame Mensah",
    isRequesterPatient: true,
    estimatedArrival: new Date(Date.now() + 20 * 60 * 1000).toISOString(),
    location: "Cardiology Ward, Block A",
    hasInsurance: true,
    insuranceProvider: "National Health Insurance",
    hasCard: true,
    notes: "Patient needs assistance with pre-surgery preparations and consultations.",
  },
  {
    id: "2",
    patientId: "p2",
    patientName: "Akosua Boateng",
    patientGender: "Female",
    patientAgeRange: "60-70",
    specialService: "Maternity",
    hospitalId: "h2",
    hospitalName: "Ridge Hospital",
    status: "accepted",
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    requesterName: "Yaw Boateng",
    isRequesterPatient: false,
    estimatedArrival: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
    location: "Maternity Ward, 2nd Floor",
    hasInsurance: false,
    hasCard: false,
    notes: "Daughter in labor, needs continuous support and coordination with medical staff.",
  },
  {
    id: "3",
    patientId: "p3",
    patientName: "Abena Osei",
    patientGender: "Female",
    patientAgeRange: "30-40",
    specialService: "Dentist",
    hospitalId: "h3",
    hospitalName: "37 Military Hospital",
    status: "pending",
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    requesterName: "Abena Osei",
    isRequesterPatient: true,
    estimatedArrival: new Date(Date.now() + 40 * 60 * 1000).toISOString(),
    location: "Dental Clinic, Ground Floor",
    hasInsurance: true,
    insuranceProvider: "Glico Health Insurance",
    hasCard: true,
  },
  {
    id: "4",
    patientId: "p4",
    patientName: "Kofi Adu",
    patientGender: "Male",
    patientAgeRange: "25-35",
    specialService: "Emergency",
    hospitalId: "h1",
    hospitalName: "Korle Bu Teaching Hospital",
    status: "accepted",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
    requesterName: "Emmanuel Adu",
    isRequesterPatient: false,
    estimatedArrival: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    location: "Emergency Ward",
    hasInsurance: false,
    hasCard: false,
    notes: "Brother involved in road accident. Needs help navigating emergency procedures and documentation.",
  },
  {
    id: "5",
    patientId: "p5",
    patientName: "Ama Sarpong",
    patientGender: "Female",
    patientAgeRange: "70-80",
    specialService: "Orthopedics",
    hospitalId: "h4",
    hospitalName: "LEKMA Hospital",
    status: "completed",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    requesterName: "Kwabena Sarpong",
    isRequesterPatient: false,
    estimatedArrival: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    location: "Orthopedic Ward, 3rd Floor",
    hasInsurance: true,
    insuranceProvider: "National Health Insurance",
    hasCard: true,
    notes: "Elderly mother with hip replacement surgery. Needed assistance with post-op care coordination.",
    invoice: {
      amount: 250,
      review: "Excellent service. Very professional and caring throughout the process.",
      paidAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: "6",
    patientId: "p6",
    patientName: "Samuel Owusu",
    patientGender: "Male",
    patientAgeRange: "15-25",
    specialService: "Pediatrics",
    hospitalId: "h2",
    hospitalName: "Ridge Hospital",
    status: "pending",
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    requesterName: "Grace Owusu",
    isRequesterPatient: false,
    estimatedArrival: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    location: "Pediatric Ward",
    hasInsurance: true,
    insuranceProvider: "Star Assurance",
    hasCard: true,
    notes: "Teenage son needs specialist consultation. Parents working and need assistance.",
  },
  {
    id: "7",
    patientId: "p7",
    patientName: "Nana Yaa Asantewaa",
    patientGender: "Female",
    patientAgeRange: "40-50",
    specialService: "Gynecology",
    hospitalId: "h5",
    hospitalName: "Nyaho Medical Centre",
    status: "accepted",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    requesterName: "Nana Yaa Asantewaa",
    isRequesterPatient: true,
    estimatedArrival: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    location: "Women's Health Center, 4th Floor",
    hasInsurance: true,
    insuranceProvider: "Enterprise Insurance",
    hasCard: true,
    notes: "Scheduled for routine procedure. Needs assistance with admission and pre-op.",
  },
  {
    id: "8",
    patientId: "p8",
    patientName: "Joseph Mensah",
    patientGender: "Male",
    patientAgeRange: "55-65",
    specialService: "Neurology",
    hospitalId: "h1",
    hospitalName: "Korle Bu Teaching Hospital",
    status: "completed",
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 47 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    requesterName: "Rebecca Mensah",
    isRequesterPatient: false,
    estimatedArrival: new Date(Date.now() - 46 * 60 * 60 * 1000).toISOString(),
    location: "Neurology Department",
    hasInsurance: true,
    insuranceProvider: "National Health Insurance",
    hasCard: true,
    notes: "Husband with neurological issues. Helped with all tests and specialist appointments.",
    invoice: {
      amount: 400,
      review: "Very knowledgeable and helpful. Made the experience much less stressful.",
      paidAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: "9",
    patientId: "p9",
    patientName: "Adjoa Frimpong",
    patientGender: "Female",
    patientAgeRange: "35-45",
    specialService: "Dermatology",
    hospitalId: "h3",
    hospitalName: "37 Military Hospital",
    status: "pending",
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    requesterName: "Adjoa Frimpong",
    isRequesterPatient: true,
    estimatedArrival: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
    location: "Dermatology Clinic",
    hasInsurance: false,
    hasCard: false,
    notes: "First time at this hospital. Need help finding departments and understanding procedures.",
  },
  {
    id: "10",
    patientId: "p10",
    patientName: "Kwesi Boateng",
    patientGender: "Male",
    patientAgeRange: "40-50",
    specialService: "General Medicine",
    hospitalId: "h4",
    hospitalName: "LEKMA Hospital",
    status: "accepted",
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    requesterName: "Kwesi Boateng",
    isRequesterPatient: true,
    estimatedArrival: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    location: "Outpatient Department",
    hasInsurance: true,
    insuranceProvider: "Hollard Insurance",
    hasCard: true,
    notes: "Follow-up consultation after recent illness. Need assistance navigating the process.",
  },
  {
    id: "11",
    patientId: "p11",
    patientName: "Efua Ansah",
    patientGender: "Female",
    patientAgeRange: "20-30",
    specialService: "Ophthalmology",
    hospitalId: "h2",
    hospitalName: "Ridge Hospital",
    status: "completed",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 4.9 * 24 * 60 * 60 * 1000).toISOString(),
    completedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    requesterName: "Efua Ansah",
    isRequesterPatient: true,
    estimatedArrival: new Date(Date.now() - 4.8 * 24 * 60 * 60 * 1000).toISOString(),
    location: "Eye Clinic",
    hasInsurance: true,
    insuranceProvider: "Vanguard Assurance",
    hasCard: true,
    notes: "Eye surgery follow-up appointments. Needed guidance throughout the process.",
    invoice: {
      amount: 180,
      review: "Great service! Very patient and understanding.",
      paidAt: new Date(Date.now() - 3.9 * 24 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: "12",
    patientId: "p12",
    patientName: "Nii Amon",
    patientGender: "Male",
    patientAgeRange: "65-75",
    specialService: "Urology",
    hospitalId: "h5",
    hospitalName: "Nyaho Medical Centre",
    status: "pending",
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    requesterName: "Naa Amon",
    isRequesterPatient: false,
    estimatedArrival: new Date(Date.now() + 25 * 60 * 1000).toISOString(),
    location: "Urology Department, 3rd Floor",
    hasInsurance: true,
    insuranceProvider: "National Health Insurance",
    hasCard: true,
    notes: "Elderly father scheduled for tests. Need help with registration and navigation.",
  },
];

export interface SessionDetail extends SessionRequest {
  requesterName: string;
  isRequesterPatient: boolean;
  estimatedArrival: string;
  location?: string;
  hasInsurance?: boolean;
  insuranceProvider?: string;
  hasCard?: boolean;
  notes?: string;
  media?: { id: string; uri: string; type: string }[];
  invoice?: {
    amount: number;
    review?: string;
    paidAt?: string;
  };
}
